Update Tagged Template Literals.mdx
While trying out provided examples, it turned out that some of them don't work.

The proposed fixes make if possible to run without 
ReferenceError: strings is not defined
ReferenceError: values is not defined
errors.

And there is an added closing </span> tag in the last example.